menu:
  Home: /
  Archives: /archives

widgets: 
- search
- category
- tag
# - twitter

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid: false
  facebook: false
  twitter: false
  google: false
  pinterest: false
  sina: false


fancybox: false

google_analytics:
rss: 